"""add registration status

Revision ID: dcc8bed352f3
Revises: 8ccbafbe00b6
Create Date: 2026-07-06 17:14:59.437229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcc8bed352f3'
down_revision: Union[str, Sequence[str], None] = '8ccbafbe00b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registrations', sa.Column('status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registrations', 'status')
    # ### end Alembic commands ###
