"""add banner and qr url

Revision ID: ff003a68475e
Revises: dfc45f07b00c
Create Date: 2026-08-28 03:41:59.489915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff003a68475e'
down_revision: Union[str, Sequence[str], None] = 'dfc45f07b00c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('banner_url', sa.String(), nullable=True))
    op.add_column('events', sa.Column('payment_qr_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'payment_qr_url')
    op.drop_column('events', 'banner_url')
    # ### end Alembic commands ###
